swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service
consumes:
  - application/json
produces:
  - application/json
paths:
  /countries:
    get:
      tags:
        - countries
      summary: countries list
      x-swagger-router-controller: universal.search
      parameters:
        - name: q
          in: query
          required: true
          type: string
        - name: page
          in: query
          required: false
          type: number
          default: 1
        - name: limit
          in: query
          type: number
          required: false
          default: 30
      responses:
        '200':
          description: countries list

    delete:
      tags:
        - delete_country
      summary: delete_country
      x-swagger-router-controller: universal.delete
      parameters:
        - name: id_delete
          in: query
          required: true
          type: string
      responses:
        '200':
          description: delete_country

    patch:
      tags:
        - country_update
      summary: country_update
      x-swagger-router-controller: universal.update
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/country'
      responses:
        '200':
          description: country_update

definitions:
  country:
    type: object
    properties:
      cca2:
        type: string
      name:
        type: object
        properties:
          common:
            type: string
           
